### ISSUE TITLE
1. Introduction

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-information-model#12]
Version -01
1.  Introduction

a) s/notional// - It either does or does not define am IM.  It does not define the idea of an IM.

b) Where are you carrying data?  suggest s/carried/required/

c) s/The SACM information model offers/The SACM architecture offers/  This is not a function of the IM.

d)  If a comsumer _can_ know who provided the information, then this should be reflected as a requirement on the IM.  If this is not true then it can be a requirement on the DM as it currently is (DM-011).

e)  Should give an example of what is meant by supplemental information.  Also, is this supplemental information defined by the IM or the DM?

**Comment by djhaynes** [comment]
a) Addressed in -04.
b) Addressed in -04.
c) Addressed in -05.
d) Text removed in -05.
e) Text removed in -05.
