### ISSUE TITLE
Section 2.3 - Dealing with Uncertainty

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-information-model#14]
Version -01
1.  I need to have some clarification on what it means to blur the difference (distinction?) between a representation and a thing represented.   I don't understand what this sentence is driving at.
2.  Combine paragraphs 2 and 3 together.  These are very related thoughts and paragraph 3 cannot stand on its own.
3.  Do you expect to have information about reputation be shared between different SACM components?  If this is the case then there might be a call for having details in the information model about reputations.
4.  I am not sure that I find the example on reputation to be useful.   There seem to be two different types of reputation that need to be considered, so perhaps an example of both would be useful.  The example that you have given is really an issue not of reputation, but of vulnerability which has been found and published in in the IM.   A completely different type of reputation would be dealing with a publisher which consistently (or inconsistently) lies about the information it has and is publishing.  And doing this without a known vulnerability.

**Comment by djhaynes** [comment]
This section was removed in -05 as part of the IM merger.
