### ISSUE TITLE
Identification and definition of attributes

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-information-model#15]
It would be nice to start by having a couple of attributes in the IM be spelled out for readers to look at.  We need to be able to see a number of things before all of the details get filled in:
1.  How are they identified (naming)
2.  How are they formatted
3.  Support requirement levels
4.  Additional attributes attached to this one (i.e. support of provenance)
5.  Data types the IM will be required to "support"
6.  Are these going to be "machine processable" for some definition of processable.

The last sentence in section 4.1 just does not cut it as a usable attribute definition.

**Comment by athiasjerome** [comment]
I concur.

Meantime, I would suggest (based on the feedback of another member) to build an abstraction layer "endpoint characterization" on top of "endpoint identification" that would describe an aggregate of various identifiers as part of the characterization

**Comment by djhaynes** [comment]
Does Section 4, 5, and 7 of the IM adequately cover this?

https://tools.ietf.org/html/draft-ietf-sacm-information-model-07#section-4
https://tools.ietf.org/html/draft-ietf-sacm-information-model-07#section-5
https://tools.ietf.org/html/draft-ietf-sacm-information-model-07#section-7

The main gap is "support requirement levels", but, I believe that is covered when selecting mandatory-to-implement information elements which has an issue here (https://github.com/sacmwg/draft-ietf-sacm-information-model/issues/65).

**Comment by djhaynes** [comment]
@jimsch did you have a chance to see if the current text satisfies your original request?

@athiasjerome with respect to endpoint characterization and identification, do the sacmStatement, sacmContentElement, and targetEndpoint IEs address your request?

**Comment by jimsch** [comment]
Yes text exists which has elements defined.  that satisfies my need.

**Comment by djhaynes** [comment]
Based on Jim's feedback and the fact he opened the issue, I am going to close it out. Please let me know if you have any questions or concerns.
