### ISSUE TITLE
Section 4.1 - Identifying Attributes

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-information-model#17]
version -02

The title of this section is ambiguous.  Are we talking about endpoint identification attributes or are we talking about how attributes are identified.  I suggest renaming the section to be "Endpoint Identification Attributes".

The first sentence would read better as

This group of attributes are designed to let a consumer identify an endpoint.  The identification of endpoints serves two purposes:

**Comment by djhaynes** [comment]
What was Section 4.1 Identifying Attributes is now Section 11.2 in -07 and is titled "Endpoint Designation".

https://tools.ietf.org/html/draft-ietf-sacm-information-model-07#section-11.1

@jimsch Does the title and corresponding text still need reworking?

Thanks,

Danny

**Comment by jimsch** [comment]
Looks fine

**Comment by djhaynes** [comment]
Given Jim's feedback and the lack of other feedback on this issue, I am going to close it out. If you have any questions or concerns, please let me know.
