### ISSUE TITLE
SACM Operations

### ISSUE THREAD

**Issue by llorenzin** [sacmwg/draft-ietf-sacm-information-model#19]
In the requirements document, we have requirements on the SACM operations (such as publishing, querying, etc.)  My impression is that those high-level SACM operations need to be defined in the information model. Do we need to add an Operations section?  If not, how will they be defined?

**Comment by sacm** [comment]
Hi,

I agree that there should be an Operations section in the SACM Info Model.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Winter  579 Park Place  Saline, MI  48176  734-944-0094
Summer  PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jimsch** [comment]
I disagree.  it makes much more sense for this type of information to be in the architecture document not this one.  these are all independent of the IM.  The only question would be the attributes needed to discover support, and it is not clear if that is protocol or IM based.

**Comment by djhaynes** [comment]
I think I would like to see the operations enumerated in the architecture along with descriptions of the different SACM components and their capabilities.  From there, we could capture any information needs (e.g. enumerations of capabilities, parameters necessary to support operations, etc.) in the IM.  Does that seem reasonable?

**Comment by david-waltermire** [comment]
+1. In the alternate architecture, Jim and I have started doing some of this. More work is needed to complete this aspect.

Dave

**Comment by djhaynes** [comment]
Are there any objections to having the operations in the architecture?  

Please let me know by 11/8. 

If there are no objections, I will move this issue to the architecture issue tracker.

**Comment by adammontville** [comment]
I haven't any objections at this point.
