### ISSUE TITLE
Stuff went missing from version 1 to version 2

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-information-model#20]
version -02

Looking at the diff, there are some sections that apparently went missing between the 01 and 02 versions of the document that were published to the IETF.  This included some of section 1.1 which was changes in version 01.

**Comment by djhaynes** [comment]
Jim, was this the diff that you were reviewing?

https://www.ietf.org/rfcdiff?url1=draft-ietf-sacm-information-model-01&url2=draft-ietf-sacm-information-model-02

**Comment by jimsch** [comment]
Yes it was

**Comment by djhaynes** [comment]
Based on Jim’s feedback on the list and the virtual interim meeting yesterday, we will proceed with pulling these missing changes back into the information model draft.  

If you have any objections to this approach, please let me know by October 2nd.

**Comment by djhaynes** [comment]
Added additional changes to change log for revision -01. I think the rest of this issue is overcome by events with the IM being a very different document than when this issue was raised.
