### ISSUE TITLE
Terminology change away from endpoint "identify" / "identifying" attributes

### ISSUE THREAD

**Issue by llorenzin** [sacmwg/draft-ietf-sacm-information-model#26]
At the Prague F2F, privacy concerns were raised around the concept of "identifying" endpoints. In many cases, the information we collect is not used to "identify" an endpoint, but rather to designate which endpoint is related to an observation or collection or guidance.

I suggest we find an alternate term to use instead of endpoint "identity" and "identifying" attributes.  One possibility is endpoint designation / designating attributes.  I'm happy to use a better term if someone can come up with something more appropriate, though!

Note that some attributes _do_ enable identification of an endpoint, so the privacy issues don't go away if we change the terminology, but I believe that changing the terminology will make it more clear that not all attributes have privacy implications.

**Comment by jimsch** [comment]
I am not sure that I see that point to this change.  The issue of identifying an endpoint is more than saying that this endpoint has the name "Fred".  Part of the issue of identifying endpoints can be done based on the properties that are associated with the endpoint.  As an example, knowing that an endpoint has a specific set of software installed on it can be enough to identify the endpoint.  Additionally, having a set of attributes assigned to an endpoint can be sufficient to identify an endpoint over time, that is an endpoint at different points in time will be able to be identified as the same endpoint.  These are all part of the "privacy" problem.

I don't see any reason to change the term from "identifying" endpoints if it makes the process of thinking about the document harder.  In my mind using "designation" does not make the process of understanding the document simpler and trying to avoid some degree of privacy questions not a sufficient driver to make this change.

**Comment by sacm** [comment]
As long as you note the privacy considerations and provide options to
protect privacy that are in line with RFC6973, the terms don't really
matter.  I'd suggest using the best terms for what you are trying to
describe and to not spend too much time on terms as that tends to hold
things up (not just in SACM, but in all WGs - terminology can consume a lot
of time).

Thanks,
Kathleen

On Thu, Sep 24, 2015 at 3:05 PM, llorenzin notifications@github.com wrote:

> At the Prague F2F, privacy concerns were raised around the concept of
> "identifying" endpoints. In many cases, the information we collect is not
> used to "identify" an endpoint, but rather to designate which endpoint is
> related to an observation or collection or guidance.
> 
> I suggest we find an alternate term to use instead of endpoint "identity"
> and "identifying" attributes. One possibility is endpoint designation /
> designating attributes. I'm happy to use a better term if someone can come
> up with something more appropriate, though!
> 
> Note that some attributes _do_ enable identification of an endpoint, so
> the privacy issues don't go away if we change the terminology, but I
> believe that changing the terminology will make it more clear that not all
> attributes have privacy implications.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sacmwg/draft-ietf-sacm-information-model/issues/26.
> 
> ---
> 
> sacm mailing list
> sacm@ietf.org
> https://www.ietf.org/mailman/listinfo/sacm

## 

Best regards,
Kathleen

**Comment by djhaynes** [comment]
duplicates #21.
