### ISSUE TITLE
how to indicate special things about information elements

### ISSUE THREAD

**Issue by djhaynes** [sacmwg/draft-ietf-sacm-information-model#39]
During the March 9, 2016 Virtual Interim Meeting, there was discussion around how to indicate whether or not information elements were useful for designation purposes, represent privacy information, or represented metadata. 

This issue came up when trying to represent information model objects, attributes, and metadata using the same IPFIX information element syntax. 

A few options that were discussed included the following.

-Add individual properties to indicate an information element is metadata, useful for designation, or represents privacy information as well as any other future properties about information elements that we may want to track.
-We could simply group the information elements in certain sections (e.g. metadata, designation, privacy, etc.). Of course, this would result in problems because information elements may fall into multiple categories (e.g. an information element could be both useful for designation purposes and represent privacy information).
-Add a new property to handle all of these special things about an information element (similar to dataTypeSemantics) or maybe just expand dataTypeSemantics. 

Proposals to solve this issue need to be expanded and sent to the list for review and discussion.

**Comment by henkbirkholz** [comment]
At the last IETF meeting, Nancy and I presented an approach to associate metadata in principle to everything a SACM component produces as a producer of information - via SACM statements with associated metadata - and to the content elements that reside in a SACM statement - via content element metadata.

https://www.ietf.org/proceedings/94/slides/slides-94-sacm-7.pdf

We will try to provide corresponding Information Model content before the next IETF meeting - that might even include examples of how information elements are composed.

**Comment by djhaynes** [comment]
Excellent and thank you!  I put a note in the IM to make sure we discuss your work and integrate it into the IM as appropriated based on the discussion.

**Comment by djhaynes** [comment]
I believe this issue has been overcome by events and can be closed out. The WG IM and I-D IM have been merged (see #41), there is a tracker to separate IEs depending on if they facilitate communication between components and endpoint information rather than by metadata, designation, etc., (see #60)  and whether or not an IE is useful for endpoint designation or represents privacy information is being left to the an organization deploying a SACM-based solution (see #17 and #7).
