### ISSUE TITLE
security considerations

### ISSUE THREAD

**Issue by dromasca** [sacmwg/draft-ietf-sacm-information-model#7]
As this document is an IM document, I would rather expect the Security Considerations section to deal with the IM elements rather than the elements that are modeled. For example - what elements are sensitive, how are repositories protected. Also refer to privacy of data about users here or in a separate Privacy Considerations section

**Comment by djhaynes** [comment]
Does the current text in the Security Considerations and Privacy Considerations sections cover this?

https://tools.ietf.org/html/draft-ietf-sacm-information-model-07#section-10
https://tools.ietf.org/html/draft-ietf-sacm-information-model-07#section-12

**Comment by djhaynes** [comment]
Since I haven't heard any feedback on this issue, I will close it out. If anyone has comments related to the Security Considerations and Privacy Considerations sections, please let me know on list and I would be happy to accommodate them.
