### ISSUE TITLE
Consider Network Topology and Location Information as Primary Identifying Attributes

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-information-model#9]
This issue was raised during an endpoint ID design team meeting (see notes for 2015-04-17).

**Comment by djhaynes** [comment]
We currently have an IE for location (see 7.52 in -08). I don't believe we have anything explicitly defined for network topology, but, someone can design one if they want and it can be used as an identifying attribute.  We also no longer have a concept of primary/secondary identifying attributes. Given that, can we close out this issue?

**Comment by sacm** [comment]
Maybe you should look at the way in which what three words is being used, or the hot desk deployments in the largest incident response center in the world in new york for desk taps!

Best Regards,

Dave

David S. Misell MBCS MIET CISSP
david.misell@bcs.org
07710380044
misell.dave on skype

**Comment by henkbirkholz** [comment]
@Dave: Could you please add a little bit more context or the URI of a resource that illustrates your input a bit?

@Danny: As SACM is focused on the enterprise domain. Maybe link-layer neighborhood (or shared-broadcast-domain, which would imply a broadcast-domain label) could be an optional attribute for layer2 interfaces? For network layer something similar like a next-hop-routing-neighbor attribute might be feasible for layer3 interfaces?

**Comment by djhaynes** [comment]
@henkbirkholz would you be interested in defining a couple of IEs for describing network topology location?

**Comment by djhaynes** [comment]
Here's a link to the three words location scheme that David mentioned.

http://what3words.com/
